moved whois to dcim
cloudless-online/ingoda pull request #2
Opened 2022-02-24 06:38 UTC by agolodyuk

Переместил whois в dcim. Теперь whois это сервис, с HTTP endpoint **_/api/v1/whois_**.
Принимает json вида 
`{"query":"some query string"}`

Отдает массив строк
`[ {"result1"}, {"result2"},...]`

В **observer/extension/autobot/whois** остался HTTP клиент.

2022-02-27 18:20 UTC, cloudless-online requested changes
Добавил комментарии по коду.

2022-02-27 18:20 UTC, alopintsev commented on observer/cmd/dcim/dcim.go
> +	var whois dcim.WhoisService = dcim.NewWhoisService(*whoisFileName)
Предлагаю обсудить, по моему whois.Run стоит убрать внутрь NewWhoisService.

2022-02-27 18:20 UTC, alopintsev commented on observer/cmd/dcim/dcim.go
> +	whois.SetHandlers(router)
HTTP потенциально только один из способов взаимодействия с объектом whois. Позже с большой вероятностью появится сущность, использующая whois напрямую через методы, или gRPC. Посмотри текущий лист-менеджер, как привязывается маршрутизация HTTP запросов.

2022-02-27 18:20 UTC, alopintsev commented on observer/cmd/dcim/dcim.go
>  	if err := http.ListenAndServe(*portNum, router); err != nil {
Предлагаю пользовать fperror т.к. сразу будет видно стэк вызова.

2022-02-27 18:20 UTC, alopintsev commented on observer/dcim/webapi.go
> +	whoisUpdateTimer = time.Minute * 30
Это лучше сделать через параметр, передаваемый при создании объекта. Сам параметр задавать через kingpin, дефолтом можно оставить 30 минут.

2022-02-27 18:20 UTC, alopintsev commented on observer/dcim/webapi.go
> +func (wh *WhoisService) Run() {
Название метода не соответствует содержимому. Предлагаю переделать в LoadData, например.

2022-02-27 18:20 UTC, alopintsev commented on observer/dcim/webapi.go
> +	go wh.update()
Судя по коду функции update, горутина будет выполняться бесконечно, даже при уже не нужном WhoisService. Можно написать тест, сделать приравнивание к одной переменной несколько экземпляров и посмотреть будет ли выход из update.

2022-02-27 18:20 UTC, cloudless-online commented on observer/dcim/webapi.go
> +	re := regexp.MustCompile(pattern)
MustCompile is like Compile but panics if the expression cannot be parsed. It simplifies safe initialization of global variables holding compiled regular expressions. 

Похоже при передаче некорректного regexp сервис умрет.

2022-02-27 18:20 UTC, cloudless-online commented on observer/dcim/webapi.go
> +	var q struct {
Зачем ради одной строки запроса делать json объект?

2022-02-27 18:20 UTC, cloudless-online commented on observer/dcim/webapi.go
> +	resetHoldTimer chan bool
Зачем здесь channel?

2022-02-27 18:20 UTC, cloudless-online commented on observer/dcim/webapi_test.go
> +func TestWhoisService(t *testing.T) {
Есть сложившаяся практика - одна функция на одну проверку.

2022-02-27 18:20 UTC, cloudless-online commented on observer/extension/autobot/whois/whois.go
> +func (b *dcimBotClient) fromService(q query) string {
Название функции не отражает суть.

2022-03-01 06:14 UTC, agolodyuk commented on observer/cmd/dcim/dcim.go
> +	var whois dcim.WhoisService = dcim.NewWhoisService(*whoisFileName)
Убрал в NewWhoisService логику инициализации сервиса.

2022-03-01 06:15 UTC, agolodyuk commented on observer/dcim/webapi.go
> +	re := regexp.MustCompile(pattern)
Добавил recover.

2022-03-01 06:15 UTC, agolodyuk commented on observer/extension/autobot/whois/whois.go
> +func (b *dcimBotClient) fromService(q query) string {
Переименовал в search.

2022-03-03 19:41 UTC, cloudless-online approved these changes
Whois moved to DCIM service

2022-03-03 19:42 UTC, merged